# Generated by Django 5.1.7 on 2025-03-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkcategory', to='posts.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkpost', to='posts.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
